sudo: required
services:
  - docker

before_install:
  - docker build -t teslake/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true teslake/react-test npm test

after_success:
  - docker build -t teslake/client ./client
  - docker build -t teslake/nginx ./nginx
  - docker build -t teslake/server ./server
  - docker build -t teslake/worker ./worker

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  - docker push teslake/client
  - docker push teslake/nginx
  - docker push teslake/server
  - docker push teslake/worker
